staging:
  profile: ~
  whoami: release/2.25.3-site-stg-out
  subdir: content/log4j/2.25.3


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 17781
# - Commit ID: e2898a0ec334cd4527b6618b3190edd1d47535f4
# - Timestamp: 2025-12-15T11:42:50Z
